stages:
  - tests
  - build
  - deploy

tests:
  stage: tests
  script:
    - pipenv install --dev --system --deploy --ignore-pipfile
    - export TXM_POSTGRES_DSN="postgresql://postgres@${POSTGRES_PORT_5432_TCP_ADDR}:5432${POSTGRES_NAME}"
    - export TXM_REDIS_DSN="redis://redis@${REDIS_PORT_6379_TCP_ADDR}:6379/0"
    - export TXM_HERMES_URL="http://localhost"
    - pytest --verbose --cov app --cov-report term-missing
  services:
    - postgres:9.4.4
    - redis:4

complexity:
  stage: tests
  script:
    - xenon --max-average A --max-modules B --max-absolute B .

style:
  stage: tests
  before_script:
    - pip install black
  script:
    - flake8 && black --line-length 120 --check .

type-check:
  stage: tests
  script:
    - mypy --ignore-missing-imports app
