version: "3.7"

x-harmonia-svc: &harmonia-svc
  image: harmonia
  build: .
  environment:
    - TXM_POSTGRES_DSN=postgresql://postgres@postgres:5432/postgres
    - TXM_REDIS_DSN=redis://redis:6379/0
    - TXM_LOG_LEVEL=debug
  volumes:
    - ./files/:/app/files/
  depends_on:
    - postgres
    - redis

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379

  migrate:
    <<: *harmonia-svc
    command: alembic upgrade head

  seed:
    <<: *harmonia-svc
    command: s/seed.py

  import-agent-acxetado:
    <<: *harmonia-svc
    command: tximport -a acxetado -y -q

  import-agent-kasisto:
    <<: *harmonia-svc
    command: tximport -a kasisto -y -q

  import-worker:
    <<: *harmonia-svc
    command: rq worker import -u redis://redis:6379/0

  matching-worker:
    <<: *harmonia-svc
    command: rq worker matching -u redis://redis:6379/0

  export-worker:
    <<: *harmonia-svc
    command: rq worker export -u redis://redis:6379/0
