version: '3'
services:
  postgres:
    image: postgres:latest

  redis:
    image: redis:latest

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672

  migrate:
    image: olympus.azurecr.io/harmonia:latest
    build: .
    command: bash -c 'echo "waiting 5s for postgres..." && sleep 5 && alembic upgrade head'
    environment:
      - POSTGRES_DSN=postgres://postgres@postgres
      - REDIS_DSN=redis://redis/0
      - AMQP_DSN=amqp://rabbitmq
    depends_on:
      - postgres

  scheme-import-director:
    image: olympus.azurecr.io/harmonia:latest
    build: .
    command: txcore import_director scheme
    environment:
      - POSTGRES_DSN=postgres://postgres@postgres
      - REDIS_DSN=redis://redis/0
      - AMQP_DSN=amqp://rabbitmq

  payment-import-director:
    image: olympus.azurecr.io/harmonia:latest
    build: .
    command: txcore import_director payment
    environment:
      - POSTGRES_DSN=postgres://postgres@postgres
      - REDIS_DSN=redis://redis/0
      - AMQP_DSN=amqp://rabbitmq

  matching-worker:
    image: olympus.azurecr.io/harmonia:latest
    build: .
    command: txcore matching_worker
    environment:
      - POSTGRES_DSN=postgres://postgres@postgres
      - REDIS_DSN=redis://redis/0
      - AMQP_DSN=amqp://rabbitmq

  import-fake-active:
    image: olympus.azurecr.io/harmonia:latest
    build: .
    command: tximport -a fake-active -y
    environment:
      - POSTGRES_DSN=postgres://postgres@postgres
      - REDIS_DSN=redis://redis/0
      - AMQP_DSN=amqp://rabbitmq

  import-fake-passive:
    image: olympus.azurecr.io/harmonia:latest
    build: .
    command: uwsgi --http 127.0.0.1:8080 --wsgi-file ../usr/local/lib/python3.6/site-packages/app/imports/agents/passive_test.py --callable app
    environment:
      - POSTGRES_DSN=postgres://postgres@postgres
      - REDIS_DSN=redis://redis/0
      - AMQP_DSN=amqp://rabbitmq

  import-fake-file:
    image: olympus.azurecr.io/harmonia:latest
    build: .
    command: tximport -a fake-file -y
    environment:
      - POSTGRES_DSN=postgres://postgres@postgres
      - REDIS_DSN=redis://redis/0
      - AMQP_DSN=amqp://rabbitmq
    volumes:
      - "./itx:/app/itx"
