version: '3'
services:
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: "harmonia"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
