"""empty message

Revision ID: 01bd04c18481
Revises: dccf9b0dbe0a
Create Date: 2024-03-11 12:29:41.762590+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "01bd04c18481"
down_revision = "dccf9b0dbe0a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pending_export", sa.Column("failure_reason", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pending_export", "failure_reason")
    # ### end Alembic commands ###
