"""add extra_fields

Revision ID: 36e71e659c6b
Revises: 6e064125f2d7
Create Date: 2023-04-17 16:31:15.305981+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36e71e659c6b'
down_revision = '6e064125f2d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export_transaction', sa.Column('extra_fields', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('transaction', sa.Column('extra_fields', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'extra_fields')
    op.drop_column('export_transaction', 'extra_fields')
    # ### end Alembic commands ###
