"""add approval code column

Revision ID: 3f09675d74e8
Revises: b06d721fff85
Create Date: 2022-05-17 10:46:46.870649+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3f09675d74e8"
down_revision = "b06d721fff85"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("export_transaction", sa.Column("auth_code", sa.String(length=50), nullable=True))
    op.add_column("export_transaction", sa.Column("approval_code", sa.String(length=50), nullable=True))
    op.add_column("export_transaction", sa.Column("settlement_key", sa.String(length=100), nullable=True))
    op.add_column("export_transaction", sa.Column("last_four", sa.String(length=4), nullable=True))
    op.add_column("export_transaction", sa.Column("expiry_month", sa.Integer(), nullable=True))
    op.add_column("export_transaction", sa.Column("expiry_year", sa.Integer(), nullable=True))
    op.add_column("export_transaction", sa.Column("payment_scheme_slug", sa.String(length=50), nullable=True))
    op.drop_constraint("matched_transaction_scheme_transaction_id_fkey", "matched_transaction", type_="foreignkey")
    op.drop_constraint("matched_transaction_payment_transaction_id_fkey", "matched_transaction", type_="foreignkey")
    op.drop_column("matched_transaction", "payment_transaction_id")
    op.drop_column("matched_transaction", "scheme_transaction_id")
    op.add_column("transaction", sa.Column("approval_code", sa.String(length=20), nullable=True))
    op.add_column("user_identity", sa.Column("expiry_month", sa.Integer(), nullable=True))
    op.add_column("user_identity", sa.Column("expiry_year", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_identity", "expiry_year")
    op.drop_column("user_identity", "expiry_month")
    op.drop_column("transaction", "approval_code")
    op.add_column(
        "matched_transaction", sa.Column("scheme_transaction_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "matched_transaction", sa.Column("payment_transaction_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        "matched_transaction_payment_transaction_id_fkey",
        "matched_transaction",
        "payment_transaction",
        ["payment_transaction_id"],
        ["id"],
    )
    op.create_foreign_key(
        "matched_transaction_scheme_transaction_id_fkey",
        "matched_transaction",
        "scheme_transaction",
        ["scheme_transaction_id"],
        ["id"],
    )
    op.drop_column("export_transaction", "payment_scheme_slug")
    op.drop_column("export_transaction", "expiry_year")
    op.drop_column("export_transaction", "expiry_month")
    op.drop_column("export_transaction", "last_four")
    op.drop_column("export_transaction", "settlement_key")
    op.drop_column("export_transaction", "approval_code")
    op.drop_column("export_transaction", "auth_code")
    # ### end Alembic commands ###
