"""ImportFileLog unique_transaction_count

Revision ID: 6b97a818f360
Revises: 454727e1a85e
Create Date: 2021-06-14 15:13:33.246636+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6b97a818f360"
down_revision = "454727e1a85e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("import_file_log", sa.Column("unique_transaction_count", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("import_file_log", "unique_transaction_count")
    # ### end Alembic commands ###
