"""Change field types from str to int

Revision ID: 6d5ea43f36a8
Revises: 663e08279b0d
Create Date: 2022-04-26 10:52:49.892638+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d5ea43f36a8'
down_revision = '663e08279b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export_transaction', sa.Column('last_four', sa.String(length=4), nullable=True))
    op.add_column('export_transaction', sa.Column('expiry_month', sa.Integer(), nullable=True))
    op.add_column('export_transaction', sa.Column('expiry_year', sa.Integer(), nullable=True))
    op.add_column('export_transaction', sa.Column('payment_scheme_slug', sa.String(length=50), nullable=True))
    op.add_column('user_identity', sa.Column('expiry_month', sa.Integer(), nullable=True))
    op.add_column('user_identity', sa.Column('expiry_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_identity', 'expiry_year')
    op.drop_column('user_identity', 'expiry_month')
    op.drop_column('export_transaction', 'payment_scheme_slug')
    op.drop_column('export_transaction', 'expiry_year')
    op.drop_column('export_transaction', 'expiry_month')
    op.drop_column('export_transaction', 'last_four')
    # ### end Alembic commands ###
