"""Add provider_slug field to SchemeTransaction and PaymentTransaction

Revision ID: b0678a97e2f7
Revises: fd616c5e3fcf
Create Date: 2020-04-20 14:02:50.273085+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b0678a97e2f7"
down_revision = "fd616c5e3fcf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payment_transaction", sa.Column("provider_slug", sa.String(length=50), nullable=False))
    op.add_column("scheme_transaction", sa.Column("payment_provider_slug", sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scheme_transaction", "payment_provider_slug")
    op.drop_column("payment_transaction", "provider_slug")
    # ### end Alembic commands ###
