"""MI_rename_indentifier_add_type

Revision ID: ba66e031b852
Revises: 40082143cebe
Create Date: 2022-07-05 12:20:09.150438+00:00

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
from app.models import IdentifierType

revision = "ba66e031b852"
down_revision = "40082143cebe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_mid_provider_mi_uc", "merchant_identifier", type_="unique")
    op.alter_column("merchant_identifier", "mid", new_column_name="identifier")
    identifiertype_enum = postgresql.ENUM(IdentifierType, name="identifiertype")
    identifiertype_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "merchant_identifier",
        sa.Column(
            "identifier_type",
            identifiertype_enum,
            nullable=True,
        ),
    )
    op.execute("UPDATE merchant_identifier SET identifier_type = 'PRIMARY'")
    op.alter_column("merchant_identifier", "identifier_type", nullable=False)
    op.create_unique_constraint(
        "_identifier_type_provider_mi_uc",
        "merchant_identifier",
        ["identifier", "identifier_type", "payment_provider_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_identifier_type_provider_mi_uc", "merchant_identifier", type_="unique")
    op.alter_column("merchant_identifier", "identifier", new_column_name="mid")
    op.drop_column("merchant_identifier", "identifier_type")
    identifiertype_enum = postgresql.ENUM(IdentifierType, name="identifiertype")
    identifiertype_enum.drop(op.get_bind())
    op.create_unique_constraint("_mid_provider_mi_uc", "merchant_identifier", ["mid", "payment_provider_id"])
    # ### end Alembic commands ###
