"""add brand id

Revision ID: d22c4e87c370
Revises: ceab707c25c5
Create Date: 2021-11-16 13:53:37.349457+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d22c4e87c370"
down_revision = "ceab707c25c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("merchant_identifier", sa.Column("brand_id", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("merchant_identifier", "brand_id")
    # ### end Alembic commands ###
