"""add new export_transaction table

Revision ID: de9c08e4f432
Revises: 3ff3ce9b30d4
Create Date: 2021-11-01 12:28:49.390788+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "de9c08e4f432"
down_revision = "3ff3ce9b30d4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "export_transaction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("transaction_id", sa.String(length=100), nullable=False),
        sa.Column("provider_slug", sa.String(length=50), nullable=False),
        sa.Column("transaction_date", sa.DateTime(), nullable=False),
        sa.Column("spend_amount", sa.Integer(), nullable=False),
        sa.Column("spend_currency", sa.String(length=3), nullable=False),
        sa.Column("loyalty_id", sa.String(length=100), nullable=False),
        sa.Column("mid", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("scheme_account_id", sa.Integer(), nullable=False),
        sa.Column("credentials", sa.Text(), nullable=False),
        sa.Column(
            "status", sa.Enum("PENDING", "EXPORTED", "EXPORT_FAILED", name="exporttransactionstatus"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("export_transaction")
    sa.Enum(name="exporttransactionstatus").drop(op.get_bind())
    # ### end Alembic commands ###
