"""add new fields to models

Revision ID: e18759665752
Revises: 2782ee0b9f9c
Create Date: 2022-05-17 12:38:41.796829+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e18759665752'
down_revision = '2782ee0b9f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export_transaction', sa.Column('auth_code', sa.String(length=50), nullable=True))
    op.add_column('export_transaction', sa.Column('approval_code', sa.String(length=50), nullable=True))
    op.add_column('export_transaction', sa.Column('last_four', sa.String(length=4), nullable=True))
    op.add_column('export_transaction', sa.Column('expiry_month', sa.Integer(), nullable=True))
    op.add_column('export_transaction', sa.Column('expiry_year', sa.Integer(), nullable=True))
    op.add_column('export_transaction', sa.Column('payment_scheme_slug', sa.String(length=50), nullable=True))
    op.add_column('transaction', sa.Column('approval_code', sa.String(length=20), nullable=True))
    op.add_column('user_identity', sa.Column('expiry_month', sa.Integer(), nullable=True))
    op.add_column('user_identity', sa.Column('expiry_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_identity', 'expiry_year')
    op.drop_column('user_identity', 'expiry_month')
    op.drop_column('transaction', 'approval_code')
    op.drop_column('export_transaction', 'payment_scheme_slug')
    op.drop_column('export_transaction', 'expiry_year')
    op.drop_column('export_transaction', 'expiry_month')
    op.drop_column('export_transaction', 'last_four')
    op.drop_column('export_transaction', 'approval_code')
    op.drop_column('export_transaction', 'auth_code')
    # ### end Alembic commands ###
