"""update useridentity and exporttransaction

Revision ID: ed5326f91d9f
Revises: 663e08279b0d
Create Date: 2022-04-01 10:36:53.127901+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ed5326f91d9f"
down_revision = "663e08279b0d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("export_transaction", sa.Column("last_four", sa.Text(), nullable=True))
    op.add_column("export_transaction", sa.Column("expiry_month", sa.Integer(), nullable=True))
    op.add_column("export_transaction", sa.Column("expiry_year", sa.Integer(), nullable=True))
    op.add_column("export_transaction", sa.Column("payment_scheme_slug", sa.String(length=50), nullable=True))
    op.add_column("user_identity", sa.Column("expiry_month", sa.Integer(), nullable=True))
    op.add_column("user_identity", sa.Column("expiry_year", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_identity", "expiry_year")
    op.drop_column("user_identity", "expiry_month")
    op.drop_column("export_transaction", "payment_scheme_slug")
    op.drop_column("export_transaction", "expiry_year")
    op.drop_column("export_transaction", "expiry_month")
    op.drop_column("export_transaction", "last_four")
    # ### end Alembic commands ###
