import random

adjectives = [
    'adroit',
    'angelic',
    'arcane',
    'austere',
    'baleful',
    'blessed',
    'blighted',
    'broken',
    'budget',
    'cruel',
    'cursed',
    'cynical',
    'despairing',
    'divine',
    'doomed',
    'eternal',
    'evil',
    'fanciful',
    'feathered',
    'flaming',
    'fluorescent',
    'frail',
    'fragile',
    'gruff',
    'hearty',
    'infernal',
    'irritating',
    'lazy',
    'leeching',
    'magnanimous',
    'magnificent',
    'malevolent',
    'merciful',
    'mischevious',
    'onerous',
    'pious',
    'robust',
    'royal',
    'sacred',
    'splendid',
    'sturdy',
    'terrible',
    'vicious',
    'woeful',
]

nouns = [
    'axe',
    'amulet',
    'blade',
    'bow',
    'brooch',
    'cloak',
    'crossbow',
    'cuirass',
    'dagger',
    'elixir',
    'flamberge',
    'flail',
    'gauntlets',
    'gladius',
    'glave',
    'gloves',
    'greaves',
    'halberd',
    'helm',
    'key',
    'lance',
    'longbow',
    'lute',
    'mantle',
    'morningstar',
    'ocarina',
    'pauldron',
    'pendant',
    'polearm',
    'potion',
    'quiver',
    'relic',
    'robe',
    'sceptre',
    'scythe',
    'spear',
    'staff',
    'tiara',
    'torch',
    'wand',
]


def new() -> str:
    return f"{random.choice(adjectives)}-{random.choice(nouns)}"
