#! /bin/bash

source s/_common

p 'sorting imports'
pipenv run isort .

p 'formatting code'
pipenv run black .

p 'linting'
pipenv run flake8

p 'checking types'
pipenv run mypy app

p 'checking complexity'
pipenv run xenon --max-average A --max-modules B --max-absolute B .
