#! /bin/bash

source s/_common

p 'truncating tables'
docker-compose exec postgres psql -U postgres -tc 'truncate import_transactions, payment_transactions, scheme_transactions restart identity' >/dev/null

p 'restarting services'
docker-compose restart
