#! /bin/bash

source s/_common

p 'building image'
docker build -t harmonia .

p 'creating services and seeding database'
docker-compose run seed

p 'starting services'
docker-compose up --scale import-director-scheme=3 --scale import-director-payment=3 --scale matching-worker=3 --scale export-director=3
