#! /bin/bash

source s/_common

set +u
service="$1"
set -u

if [ -z "$service" ]; then
    p "logs for all containers"
    docker-compose logs -f
else
    p "logs for $service"
    docker-compose logs -f "$service"
fi
