#! /bin/bash

source s/_common

p 'removing existing temp db if exists'
docker rm -f txm-makemigration-db || true

p 'starting temp db'
docker run -d --rm --name txm-makemigration-db -p 55555:5432 postgres:latest
export TXM_POSTGRES_DSN=postgresql://postgres@localhost:55555

p 'waiting for db to start'
sleep 5

p 'migrating temp db'
pipenv run alembic upgrade head

p 'making new migration'
pipenv run alembic revision --autogenerate

p 'testing new migration'
pipenv run alembic upgrade head

p 'stopping temp db'
docker stop txm-makemigration-db
