#! /bin/bash

source s/_common

p 'starting temp db'
docker run -d --name makemigration-db -p 5432:5432 postgres:latest

p 'waiting for db to start'
sleep 5

p 'migrating temp db'
pipenv run alembic upgrade head

p 'making new migration'
pipenv run alembic revision --autogenerate

p 'testing new migration'
pipenv run alembic upgrade head

p 'removing temp db'
docker rm -f makemigration-db
