#! /bin/bash

source s/_common

s/services

# change these to match your hermes source directories
export HERMES_PATH="$HOME/Code/hermes"
export HERMES_PY="$HOME/.local/share/virtualenvs/hermes-mM11d_vp/bin/python"

p 'setting up hermes'
cp hermes-seed_iceland.json /tmp/hermes-seed_iceland.json
pushd "$HERMES_PATH"
"$HERMES_PY" manage.py loaddata /tmp/hermes-seed_iceland.json
popd

p 'seeding database'
s/seed

p 'waiting for api to start'
until curl -sL http://127.0.0.1:5000/txm/status/ >/dev/null; do sleep 2; done

p 'producing transactions for Iceland'
s/producer_iceland
pipenv run tximport -a iceland-bonus-card -y --once

p 'running import worker for iceland'
TXM_RQ_QUEUES='import' pipenv run rq worker --burst -c rq_worker_settings

p 'running matching worker for iceland'
TXM_RQ_QUEUES='matching' pipenv run rq worker --burst -c rq_worker_settings

p 'running export worker for iceland'
TXM_RQ_QUEUES='export' pipenv run rq worker --burst -c rq_worker_settings
