#! /bin/bash

source s/_common

s/services

# change these to match your hermes source directories
export HERMES_PATH="$HOME/projects/olympus/hermes"
export HERMES_PY="$HOME/.virtualenvs/hermes-aqZO6leb/bin/python"

p 'setting up hermes'
cp hermes-seed.json /tmp/hermes-seed.json
pushd "$HERMES_PATH"
"$HERMES_PY" manage.py loaddata /tmp/hermes-seed.json
popd

p 'seeding database'
pipenv run s/seed.py

p 'producing transaction files'
pipenv run s/producer.py -n 1 --scheme-file files/imports/example-loyalty-scheme/transactions-2018-12-04 --payment-file files/imports/example-payment-provider/card-tx-20181204

p 'running payment import agent'
pipenv run tximport --agent example-payment-provider --no-user-input --quiet --once

p 'running import worker'
TXM_RQ_QUEUES='import' pipenv run rq worker --burst -c rq_worker_settings

p 'running matching worker'
TXM_RQ_QUEUES='matching' pipenv run rq worker --burst -c rq_worker_settings

p 'running scheme import agent'
pipenv run tximport --agent example-loyalty-scheme --no-user-input --quiet --once

p 'running import worker'
TXM_RQ_QUEUES='import' pipenv run rq worker --burst -c rq_worker_settings

p 'running matching worker'
TXM_RQ_QUEUES='matching' pipenv run rq worker --burst -c rq_worker_settings

p 'running export worker'
TXM_RQ_QUEUES='export' pipenv run rq worker --burst -c rq_worker_settings
