#! /bin/bash

source s/_common

s/services

p 'producing a transaction'
pipenv run s/producer.py --once

p 'running import directors'
pipenv run txcore import-director --once scheme
pipenv run txcore import-director --once payment

p 'running matching worker'
pipenv run txcore matching-worker --debug
