#! /bin/bash

source s/_common

s/rmservices

p 'creating postgres'
docker run \
	-d \
	-p51234:5432 \
	--name txm-postgres \
	-e POSTGRES_HOST_AUTH_METHOD=trust \
	postgres

p 'creating redis'
docker run \
	-d \
	-p61234:6379 \
	--name txm-redis \
	redis

p 'creating rabbitmq'
docker run \
	-d \
	-p55672:5672 \
	-p55673:15672 \
	--name txm-rabbitmq \
	rabbitmq:3-management

p 'giving postgres a chance to start'
sleep 3

p 'creating harmonia database'
docker exec -it txm-postgres psql -U postgres -c 'create database harmonia;'

s/migrate
